default_context:
  project_name: 'webtronics'
  project_slug: 'webtronics'
  domain_main: 'webtronics.com'
  domain_staging: 'stag.webtronics.com'
  docker_swarm_stack_name_main: 'webtronics-com'
  docker_swarm_stack_name_staging: 'stag-webtronics-com'
  secret_key: 'changethis'
  first_superuser: 'admin@webtronics.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.webtronics.com", "https://stag.webtronics.com", "https://webtronics.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@webtronics.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@webtronics.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'webtronics.com'
  traefik_constraint_tag_staging: 'stag.webtronics.com'
  traefik_public_constraint_tag: 'traefik-public'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  _template: ./
