"""Add likes:

Revision ID: 55157dee9fb2
Revises: fb6b082de0e1
Create Date: 2023-01-09 11:52:01.260905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55157dee9fb2'
down_revision = 'fb6b082de0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
