"""Delete

Revision ID: 89b846cdd8de
Revises: 1e5a6328aef1
Create Date: 2023-01-09 16:43:34.177102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b846cdd8de'
down_revision = '1e5a6328aef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_dislikes')
    op.drop_table('post_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_likes_user_id_fkey')
    )
    op.create_table('post_dislikes',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_dislikes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_dislikes_user_id_fkey')
    )
    # ### end Alembic commands ###
